export const dict = {
  'common.views': { id: 'kali dilihat', en: 'views' },
  'common.viewed': { id: 'dilihat', en: 'views' },
  'common.visitors': { id: 'pengunjung', en: 'visitors' },
  'common.fromGoogle': { id: 'dari Google', en: 'from Google' },
  'common.visits': { id: 'kunjungan', en: 'visits' },
  'common.backToTop': { id: 'Kembali ke atas', en: 'Back to top' },
  'common.rightsReserved': { id: '© {{year}} CehaDev. Hak cipta dilindungi.', en: '© {{year}} CehaDev. All rights reserved.' },
  'common.motto': { id: 'Bangun. Belajar. Rusak. Perbaiki. Ulangi.', en: 'Build. Learn. Break. Fix. Repeat.' },

  'nav.home': { id: 'Beranda', en: 'Home' },
  'nav.about': { id: 'Tentang', en: 'About' },
  'nav.projects': { id: 'Proyek', en: 'Projects' },
  'nav.articles': { id: 'Artikel', en: 'Articles' },
  'nav.contact': { id: 'Kontak', en: 'Contact' },
  'nav.switchLang': { id: 'Ganti bahasa', en: 'Switch language' },
  'nav.downloadCv': { id: 'Unduh CV', en: 'Download CV' },
  'nav.openMenu': { id: 'Buka menu', en: 'Open menu' },
  'nav.closeMenu': { id: 'Tutup menu', en: 'Close menu' },
  'nav.toggleThemeDark': { id: 'Aktifkan mode terang', en: 'Enable light mode' },
  'nav.toggleThemeLight': { id: 'Aktifkan mode gelap', en: 'Enable dark mode' },
  'nav.mainAria': { id: 'Navigasi utama', en: 'Main navigation' },

  'footer.quickLinks': { id: 'Tautan Cepat', en: 'Quick Links' },
  'footer.contact': { id: 'Kontak', en: 'Contact' },
  'footer.letsWorkTogether': { id: 'Mari bekerja sama', en: "Let's work together" },
  'footer.blurb': {
    id: '{{role}} yang membangun produk digital modern, cepat, dan mudah digunakan.',
    en: '{{role}} who builds modern, fast, and easy-to-use digital products.'
  },
  'footer.faqTitle': { id: 'Pertanyaan yang Sering Diajukan', en: 'Frequently Asked Questions' },
  'footer.faqHead': { id: 'Ada pertanyaan', en: 'Any questions' },
  'footer.faqDesc': {
    id: 'Pilih pertanyaan di bawah untuk mengirimnya langsung ke kolom chat, atau tulis pertanyaan Anda sendiri.',
    en: 'Pick a question below to send it straight to the chat, or write your own.'
  },
  'footer.openChat': { id: 'Buka kolom chat', en: 'Open chat' },
  'footer.emailLabel': { id: 'Email', en: 'Email' },
  'footer.phoneLabel': { id: 'Telepon', en: 'Phone' },
  'footer.locationLabel': { id: 'Lokasi', en: 'Location' },
  'footer.ctaDesc': { id: 'Punya project atau ide? Mari diskusikan.', en: 'Have a project or idea? Let\'s discuss it.' },
  'footer.contactMe': { id: 'Hubungi Saya', en: 'Contact Me' },

  'contact.title': { id: 'Kirim Pesan', en: 'Send Me a Message' },
  'contact.desc': { id: 'Isi form di bawah, saya akan segera membalasnya.', en: "Fill out the form below and I'll reply soon." },
  'contact.name': { id: 'Nama Anda', en: 'Your Name' },
  'contact.email': { id: 'Email Anda', en: 'Your Email' },
  'contact.subject': { id: 'Subjek', en: 'Subject' },
  'contact.message': { id: 'Pesan Anda', en: 'Your Message' },
  'contact.namePlaceholder': { id: 'Nama lengkap', en: 'Full name' },
  'contact.emailPlaceholder': { id: 'nama@email.com', en: 'name@email.com' },
  'contact.subjectPlaceholder': { id: 'Tujuan pesan', en: 'Message subject' },
  'contact.messagePlaceholder': { id: 'Tulis pesan Anda di sini...', en: 'Write your message here...' },
  'contact.send': { id: 'Kirim Pesan', en: 'Send Message' },
  'contact.sending': { id: 'Mengirim...', en: 'Sending...' },
  'contact.success': {
    id: 'Pesan berhasil dikirim! Terima kasih, saya akan segera membalas.',
    en: "Message sent successfully! Thank you, I'll reply soon."
  },
  'contact.errorFallback': { id: 'Gagal mengirim pesan, coba lagi.', en: 'Failed to send message, try again.' },
  'contact.privacy': { id: 'Data Anda aman bersama saya', en: 'Your data is safe with me' },
  'contact.reqName': { id: 'Nama wajib diisi', en: 'Name is required' },
  'contact.reqEmail': { id: 'Email tidak valid', en: 'Invalid email' },
  'contact.reqSubject': { id: 'Subjek wajib diisi', en: 'Subject is required' },
  'contact.reqMessage': { id: 'Pesan minimal 10 karakter', en: 'Message must be at least 10 characters' },

  'chat.aria': { id: 'Chat dengan CehaDev', en: 'Chat with CehaDev' },
  'chat.title': { id: 'Dukungan CehaDev', en: 'CehaDev Support' },
  'chat.resolved': { id: 'Percakapan selesai', en: 'Conversation closed' },
  'chat.online': { id: 'Online — biasanya membalas cepat', en: 'Online — usually replies fast' },
  'chat.close': { id: 'Tutup chat', en: 'Close chat' },
  'chat.greeting': { id: 'Hai! Ada yang bisa saya bantu?', en: 'Hi! How can I help?' },
  'chat.hint': {
    id: 'Pilih salah satu pertanyaan di bawah, atau tulis pesan Anda langsung.',
    en: 'Choose a question below or type your message.'
  },
  'chat.namePlaceholder': { id: 'Nama', en: 'Name' },
  'chat.emailPlaceholder': { id: 'Email', en: 'Email' },
  'chat.writeMessage': { id: 'Tulis pesan Anda...', en: 'Write your message...' },
  'chat.typeReply': { id: 'Ketik balasan...', en: 'Type a reply...' },
  'chat.send': { id: 'Kirim pesan', en: 'Send message' },
  'chat.error': { id: 'Gagal mengirim pesan', en: 'Failed to send message' },
  'chat.open': { id: 'Buka chat', en: 'Open chat' },

  'projectCard.viewProject': { id: 'Lihat Project', en: 'View Project' },
  'projectCard.viewDemoAria': { id: 'Lihat demo {{title}}', en: 'View demo {{title}}' },
  'projectCard.featured': { id: 'Unggulan', en: 'Featured' },

  'articles.badge': { id: 'Blog & Catatan', en: 'Blog & Notes' },
  'articles.heroHead1': { id: 'Artikel', en: 'Latest' },
  'articles.heroHead2': { id: '& Tulisan', en: 'Articles' },
  'articles.heroDesc': {
    id: 'Catatan, tutorial, dan pemikiran seputar dunia web development — ditulis agar apa yang dipelajari tidak hilang.',
    en: 'Notes, tutorials, and thoughts about web development — written so what I learn never goes to waste.'
  },
  'articles.allCategory': { id: 'Semua', en: 'All' },
  'articles.filterAria': { id: 'Filter kategori artikel', en: 'Filter articles by category' },
  'articles.empty': { id: 'Belum ada artikel di kategori ini.', en: 'No articles in this category yet.' },
  'articles.readTime': { id: '{{min}} mnt baca', en: '{{min}} min read' },
  'articles.publishedOn': { id: 'Diterbitkan', en: 'Published' },
  'articles.updatedOn': { id: 'Diperbarui', en: 'Updated' },
  'articles.backToList': { id: 'Semua Artikel', en: 'All Articles' },
  'articles.notFound': { id: 'Artikel tidak ditemukan', en: 'Article not found' },
  'articles.tableOfContents': { id: 'Daftar isi', en: 'Table of contents' },
  'articles.searchPlaceholder': { id: 'Cari judul, tag...', en: 'Search title, tag...' },
  'articles.searchAria': { id: 'Cari artikel', en: 'Search articles' },
  'articles.sortAria': { id: 'Urutkan artikel', en: 'Sort articles' },
  'articles.sortNewest': { id: 'Terbaru', en: 'Newest' },
  'articles.sortOldest': { id: 'Terlama', en: 'Oldest' },
  'articles.sortAz': { id: 'Judul A-Z', en: 'Title A-Z' },
  'articles.tagFilterAria': { id: 'Filter artikel berdasarkan tag', en: 'Filter articles by tag' },
  'articles.loadMore': { id: 'Muat Lebih Banyak', en: 'Load More' },
  'articles.showingOf': { id: 'Menampilkan {{shown}} dari {{total}} artikel', en: 'Showing {{shown}} of {{total}} articles' },
  'articles.noResults': { id: 'Tidak ada artikel yang cocok dengan pencarian/filter Anda.', en: 'No articles match your search or filters.' },
  'articles.resetFilter': { id: 'Reset Filter', en: 'Reset Filters' },
  'articles.latestPost': { id: 'Artikel Terbaru', en: 'Latest Post' },
  'articles.readNow': { id: 'Baca Sekarang', en: 'Read Now' },
  'articles.share': { id: 'Bagikan', en: 'Share' },
  'articles.copyLink': { id: 'Salin tautan', en: 'Copy link' },
  'articles.linkCopied': { id: 'Tautan disalin!', en: 'Link copied!' },
  'articles.shareWhatsapp': { id: 'Bagikan ke WhatsApp', en: 'Share to WhatsApp' },
  'articles.shareX': { id: 'Bagikan ke X', en: 'Share to X' },
  'articles.shareFacebook': { id: 'Bagikan ke Facebook', en: 'Share to Facebook' },
  'articles.prevArticle': { id: 'Sebelumnya', en: 'Previous' },
  'articles.nextArticle': { id: 'Selanjutnya', en: 'Next' },
  'articleCard.readArticle': { id: 'Baca selengkapnya', en: 'Read article' }
} as const

export type DictKey = keyof typeof dict
